### ISSUE TITLE
SETUP: "Add card details to Heroku"

### ISSUE THREAD

**Issue by jferreira** [jferreira/MS-V1_Media-Sifter_BACKEND-RAILS#1]

**Comment by jferreira** [comment]
<img width="1888" alt="screen shot 2017-08-08 at 20 41 18" src="https://user-images.githubusercontent.com/93381/29088642-128bf960-7c7a-11e7-8da7-722b18ab7ad0.png">

**Comment by chill5018** [comment]
Awe yeah doggy
